# Based on https://github.com/pywinauto/pywinauto
#
# Hint: before committing any changes in the yaml file verify it in 
# the yaml online parser: http://yaml-online-parser.appspot.com/
#

# fetch repository as a zip archive
shallow_clone: true                 # default is "false"

environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

#os:
#  - unstable # Unstable worker image with logged in user, desktop and interactive build agent

install:
  # Some listings for debug only
  #- ECHO "Filesystem root:"
  #- ps: "ls \"C:/\""
  #- ECHO "Notepad location "
  #- ps: "ls C:\\Windows\\System32\\notepad.exe"

   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))

   - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

   # Install the build dependencies of the project.
   - "%CMD_IN_ENV% pip install -r dev-requirements.txt"

   # Install pywinauto from the trunk
   - "%CMD_IN_ENV% pip install -e git+https://github.com/pywinauto/pywinauto.git@master#egg=pywinauto-trunk"
   # - "%CMD_IN_ENV% pip install -e git+https://github.com/pywinauto/pywinauto.git@5b2b8a6082cc14154b32a94178c11a4c3a574701#egg=pywinauto"

   # install wxPython
   - "%CMD_IN_ENV% powershell ./ci/install.ps1"

   # install wxPython
   - "%CMD_IN_ENV% powershell ./ci/install.ps1"

   # Print python modules
   - "%CMD_IN_ENV% pip freeze"

build: off  # disable automatic builds


before_build:
  # Download sample apps
  - "%CMD_IN_ENV% svn checkout https://github.com/pywinauto/pywinauto/trunk/apps ./apps"
  # Run unittests
  - "%CMD_IN_ENV% python -m unittest discover"

build_script:
  # Print python modules again
  - "%CMD_IN_ENV% pip freeze"
  # Build UI
  - "%CMD_IN_ENV% powershell ./ci/build.ps1"


#test_script:
#  # Run UI tests


artifacts:
  # Archive the generated coverage report in the ci.appveyor.com build report.
  - path: swapy*.exe
    name: binaries

on_failure:
  - "7z a screenshots.zip scr*.jpg"
  - "appveyor PushArtifact screenshots.zip"
